'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Countries',
      [
        {
          countryCode: 'AD',
          countryName: 'Andorra',
          phoneCode: '376',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AE',
          countryName: 'United Arab Emirates',
          phoneCode: '971',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AF',
          countryName: 'Afghanistan',
          phoneCode: '93',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AG',
          countryName: 'Antigua and Barbuda',
          phoneCode: '1-268',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AI',
          countryName: 'Anguilla',
          phoneCode: '1-264',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AL',
          countryName: 'Albania',
          phoneCode: '355',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AM',
          countryName: 'Armenia',
          phoneCode: '374',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AO',
          countryName: 'Angola',
          phoneCode: '244',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AQ',
          countryName: 'Antarctica',
          phoneCode: '672',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AR',
          countryName: 'Argentina',
          phoneCode: '54',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AS',
          countryName: 'American Samoa',
          phoneCode: '1-684',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AT',
          countryName: 'Austria',
          phoneCode: '43',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AU',
          countryName: 'Australia',
          phoneCode: '61',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AW',
          countryName: 'Aruba',
          phoneCode: '297',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AX',
          countryName: 'Alland Islands',
          phoneCode: '358',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'AZ',
          countryName: 'Azerbaijan',
          phoneCode: '994',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BA',
          countryName: 'Bosnia and Herzegovina',
          phoneCode: '387',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BB',
          countryName: 'Barbados',
          phoneCode: '1-246',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BD',
          countryName: 'Bangladesh',
          phoneCode: '880',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BE',
          countryName: 'Belgium',
          phoneCode: '32',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BF',
          countryName: 'Burkina Faso',
          phoneCode: '226',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BG',
          countryName: 'Bulgaria',
          phoneCode: '359',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BH',
          countryName: 'Bahrain',
          phoneCode: '973',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BI',
          countryName: 'Burundi',
          phoneCode: '257',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BJ',
          countryName: 'Benin',
          phoneCode: '229',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BL',
          countryName: 'Saint Barthelemy',
          phoneCode: '590',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BM',
          countryName: 'Bermuda',
          phoneCode: '1-441',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BN',
          countryName: 'Brunei Darussalam',
          phoneCode: '673',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BO',
          countryName: 'Bolivia',
          phoneCode: '591',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BR',
          countryName: 'Brazil',
          phoneCode: '55',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BS',
          countryName: 'Bahamas',
          phoneCode: '1-242',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BT',
          countryName: 'Bhutan',
          phoneCode: '975',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BV',
          countryName: 'Bouvet Island',
          phoneCode: '47',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BW',
          countryName: 'Botswana',
          phoneCode: '267',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BY',
          countryName: 'Belarus',
          phoneCode: '375',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'BZ',
          countryName: 'Belize',
          phoneCode: '501',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CA',
          countryName: 'Canada',
          phoneCode: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CC',
          countryName: 'Cocos (Keeling) Islands',
          phoneCode: '61',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CD',
          countryName: 'Congo, Democratic Republic of the',
          phoneCode: '243',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CF',
          countryName: 'Central African Republic',
          phoneCode: '236',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CG',
          countryName: 'Congo, Republic of the',
          phoneCode: '242',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CH',
          countryName: 'Switzerland',
          phoneCode: '41',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CI',
          countryName: "Cote d'Ivoire",
          phoneCode: '225',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CK',
          countryName: 'Cook Islands',
          phoneCode: '682',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CL',
          countryName: 'Chile',
          phoneCode: '56',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CM',
          countryName: 'Cameroon',
          phoneCode: '237',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CN',
          countryName: 'China',
          phoneCode: '86',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CO',
          countryName: 'Colombia',
          phoneCode: '57',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CR',
          countryName: 'Costa Rica',
          phoneCode: '506',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CU',
          countryName: 'Cuba',
          phoneCode: '53',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CV',
          countryName: 'Cape Verde',
          phoneCode: '238',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CW',
          countryName: 'Curacao',
          phoneCode: '599',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CX',
          countryName: 'Christmas Island',
          phoneCode: '61',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CY',
          countryName: 'Cyprus',
          phoneCode: '357',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'CZ',
          countryName: 'Czech Republic',
          phoneCode: '420',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'DE',
          countryName: 'Germany',
          phoneCode: '49',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'DJ',
          countryName: 'Djibouti',
          phoneCode: '253',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'DK',
          countryName: 'Denmark',
          phoneCode: '45',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'DM',
          countryName: 'Dominica',
          phoneCode: '1-767',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'DO',
          countryName: 'Dominican Republic',
          phoneCode: '1-809',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'DZ',
          countryName: 'Algeria',
          phoneCode: '213',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'EC',
          countryName: 'Ecuador',
          phoneCode: '593',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'EE',
          countryName: 'Estonia',
          phoneCode: '372',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'EG',
          countryName: 'Egypt',
          phoneCode: '20',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'EH',
          countryName: 'Western Sahara',
          phoneCode: '212',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ER',
          countryName: 'Eritrea',
          phoneCode: '291',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ES',
          countryName: 'Spain',
          phoneCode: '34',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ET',
          countryName: 'Ethiopia',
          phoneCode: '251',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'FI',
          countryName: 'Finland',
          phoneCode: '358',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'FJ',
          countryName: 'Fiji',
          phoneCode: '679',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'FK',
          countryName: 'Falkland Islands (Malvinas)',
          phoneCode: '500',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'FM',
          countryName: 'Micronesia, Federated States of',
          phoneCode: '691',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'FO',
          countryName: 'Faroe Islands',
          phoneCode: '298',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'FR',
          countryName: 'France',
          phoneCode: '33',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GA',
          countryName: 'Gabon',
          phoneCode: '241',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GB',
          countryName: 'United Kingdom',
          phoneCode: '44',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GD',
          countryName: 'Grenada',
          phoneCode: '1-473',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GE',
          countryName: 'Georgia',
          phoneCode: '995',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GF',
          countryName: 'French Guiana',
          phoneCode: '594',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GG',
          countryName: 'Guernsey',
          phoneCode: '44',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GH',
          countryName: 'Ghana',
          phoneCode: '233',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GI',
          countryName: 'Gibraltar',
          phoneCode: '350',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GL',
          countryName: 'Greenland',
          phoneCode: '299',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GM',
          countryName: 'Gambia',
          phoneCode: '220',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GN',
          countryName: 'Guinea',
          phoneCode: '224',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GP',
          countryName: 'Guadeloupe',
          phoneCode: '590',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GQ',
          countryName: 'Equatorial Guinea',
          phoneCode: '240',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GR',
          countryName: 'Greece',
          phoneCode: '30',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GS',
          countryName: 'South Georgia and the South Sandwich Islands',
          phoneCode: '500',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GT',
          countryName: 'Guatemala',
          phoneCode: '502',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GU',
          countryName: 'Guam',
          phoneCode: '1-671',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GW',
          countryName: 'Guinea-Bissau',
          phoneCode: '245',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'GY',
          countryName: 'Guyana',
          phoneCode: '592',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'HK',
          countryName: 'Hong Kong',
          phoneCode: '852',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'HM',
          countryName: 'Heard Island and McDonald Islands',
          phoneCode: '672',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'HN',
          countryName: 'Honduras',
          phoneCode: '504',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'HR',
          countryName: 'Croatia',
          phoneCode: '385',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'HT',
          countryName: 'Haiti',
          phoneCode: '509',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'HU',
          countryName: 'Hungary',
          phoneCode: '36',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ID',
          countryName: 'Indonesia',
          phoneCode: '62',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IE',
          countryName: 'Ireland',
          phoneCode: '353',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IL',
          countryName: 'Israel',
          phoneCode: '972',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IM',
          countryName: 'Isle of Man',
          phoneCode: '44',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IN',
          countryName: 'India',
          phoneCode: '91',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IO',
          countryName: 'British Indian Ocean Territory',
          phoneCode: '246',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IQ',
          countryName: 'Iraq',
          phoneCode: '964',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IR',
          countryName: 'Iran, Islamic Republic of',
          phoneCode: '98',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IS',
          countryName: 'Iceland',
          phoneCode: '354',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'IT',
          countryName: 'Italy',
          phoneCode: '39',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'JE',
          countryName: 'Jersey',
          phoneCode: '44',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'JM',
          countryName: 'Jamaica',
          phoneCode: '1-876',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'JO',
          countryName: 'Jordan',
          phoneCode: '962',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'JP',
          countryName: 'Japan',
          phoneCode: '81',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KE',
          countryName: 'Kenya',
          phoneCode: '254',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KG',
          countryName: 'Kyrgyzstan',
          phoneCode: '996',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KH',
          countryName: 'Cambodia',
          phoneCode: '855',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KI',
          countryName: 'Kiribati',
          phoneCode: '686',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KM',
          countryName: 'Comoros',
          phoneCode: '269',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KN',
          countryName: 'Saint Kitts and Nevis',
          phoneCode: '1-869',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KP',
          countryName: "Korea, Democratic People's Republic of",
          phoneCode: '850',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KR',
          countryName: 'Korea, Republic of',
          phoneCode: '82',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KW',
          countryName: 'Kuwait',
          phoneCode: '965',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KY',
          countryName: 'Cayman Islands',
          phoneCode: '1-345',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'KZ',
          countryName: 'Kazakhstan',
          phoneCode: '7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LA',
          countryName: "Lao People's Democratic Republic",
          phoneCode: '856',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LB',
          countryName: 'Lebanon',
          phoneCode: '961',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LC',
          countryName: 'Saint Lucia',
          phoneCode: '1-758',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LI',
          countryName: 'Liechtenstein',
          phoneCode: '423',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LK',
          countryName: 'Sri Lanka',
          phoneCode: '94',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LR',
          countryName: 'Liberia',
          phoneCode: '231',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LS',
          countryName: 'Lesotho',
          phoneCode: '266',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LT',
          countryName: 'Lithuania',
          phoneCode: '370',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LU',
          countryName: 'Luxembourg',
          phoneCode: '352',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LV',
          countryName: 'Latvia',
          phoneCode: '371',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'LY',
          countryName: 'Libya',
          phoneCode: '218',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MA',
          countryName: 'Morocco',
          phoneCode: '212',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MC',
          countryName: 'Monaco',
          phoneCode: '377',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MD',
          countryName: 'Moldova, Republic of',
          phoneCode: '373',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ME',
          countryName: 'Montenegro',
          phoneCode: '382',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MF',
          countryName: 'Saint Martin (French part)',
          phoneCode: '590',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MG',
          countryName: 'Madagascar',
          phoneCode: '261',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MH',
          countryName: 'Marshall Islands',
          phoneCode: '692',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MK',
          countryName: 'Macedonia, the Former Yugoslav Republic of',
          phoneCode: '389',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ML',
          countryName: 'Mali',
          phoneCode: '223',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MM',
          countryName: 'Myanmar',
          phoneCode: '95',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MN',
          countryName: 'Mongolia',
          phoneCode: '976',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MO',
          countryName: 'Macao',
          phoneCode: '853',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MP',
          countryName: 'Northern Mariana Islands',
          phoneCode: '1-670',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MQ',
          countryName: 'Martinique',
          phoneCode: '596',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MR',
          countryName: 'Mauritania',
          phoneCode: '222',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MS',
          countryName: 'Montserrat',
          phoneCode: '1-664',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MT',
          countryName: 'Malta',
          phoneCode: '356',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MU',
          countryName: 'Mauritius',
          phoneCode: '230',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MV',
          countryName: 'Maldives',
          phoneCode: '960',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MW',
          countryName: 'Malawi',
          phoneCode: '265',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MX',
          countryName: 'Mexico',
          phoneCode: '52',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MY',
          countryName: 'Malaysia',
          phoneCode: '60',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'MZ',
          countryName: 'Mozambique',
          phoneCode: '258',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NA',
          countryName: 'Namibia',
          phoneCode: '264',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NC',
          countryName: 'New Caledonia',
          phoneCode: '687',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NE',
          countryName: 'Niger',
          phoneCode: '227',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NF',
          countryName: 'Norfolk Island',
          phoneCode: '672',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NG',
          countryName: 'Nigeria',
          phoneCode: '234',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NI',
          countryName: 'Nicaragua',
          phoneCode: '505',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NL',
          countryName: 'Netherlands',
          phoneCode: '31',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NO',
          countryName: 'Norway',
          phoneCode: '47',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NP',
          countryName: 'Nepal',
          phoneCode: '977',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NR',
          countryName: 'Nauru',
          phoneCode: '674',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NU',
          countryName: 'Niue',
          phoneCode: '683',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'NZ',
          countryName: 'New Zealand',
          phoneCode: '64',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'OM',
          countryName: 'Oman',
          phoneCode: '968',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PA',
          countryName: 'Panama',
          phoneCode: '507',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PE',
          countryName: 'Peru',
          phoneCode: '51',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PF',
          countryName: 'French Polynesia',
          phoneCode: '689',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PG',
          countryName: 'Papua New Guinea',
          phoneCode: '675',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PH',
          countryName: 'Philippines',
          phoneCode: '63',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PK',
          countryName: 'Pakistan',
          phoneCode: '92',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PL',
          countryName: 'Poland',
          phoneCode: '48',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PM',
          countryName: 'Saint Pierre and Miquelon',
          phoneCode: '508',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PN',
          countryName: 'Pitcairn',
          phoneCode: '870',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PR',
          countryName: 'Puerto Rico',
          phoneCode: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PS',
          countryName: 'Palestine, State of',
          phoneCode: '970',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PT',
          countryName: 'Portugal',
          phoneCode: '351',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PW',
          countryName: 'Palau',
          phoneCode: '680',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'PY',
          countryName: 'Paraguay',
          phoneCode: '595',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'QA',
          countryName: 'Qatar',
          phoneCode: '974',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'RE',
          countryName: 'Reunion',
          phoneCode: '262',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'RO',
          countryName: 'Romania',
          phoneCode: '40',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'RS',
          countryName: 'Serbia',
          phoneCode: '381',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'RU',
          countryName: 'Russian Federation',
          phoneCode: '7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'RW',
          countryName: 'Rwanda',
          phoneCode: '250',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SA',
          countryName: 'Saudi Arabia',
          phoneCode: '966',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SB',
          countryName: 'Solomon Islands',
          phoneCode: '677',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SC',
          countryName: 'Seychelles',
          phoneCode: '248',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SD',
          countryName: 'Sudan',
          phoneCode: '249',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SE',
          countryName: 'Sweden',
          phoneCode: '46',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SG',
          countryName: 'Singapore',
          phoneCode: '65',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SH',
          countryName: 'Saint Helena',
          phoneCode: '290',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SI',
          countryName: 'Slovenia',
          phoneCode: '386',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SJ',
          countryName: 'Svalbard and Jan Mayen',
          phoneCode: '47',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SK',
          countryName: 'Slovakia',
          phoneCode: '421',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SL',
          countryName: 'Sierra Leone',
          phoneCode: '232',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SM',
          countryName: 'San Marino',
          phoneCode: '378',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SN',
          countryName: 'Senegal',
          phoneCode: '221',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SO',
          countryName: 'Somalia',
          phoneCode: '252',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SR',
          countryName: 'Suriname',
          phoneCode: '597',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SS',
          countryName: 'South Sudan',
          phoneCode: '211',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ST',
          countryName: 'Sao Tome and Principe',
          phoneCode: '239',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SV',
          countryName: 'El Salvador',
          phoneCode: '503',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SX',
          countryName: 'Sint Maarten (Dutch part)',
          phoneCode: '1-721',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SY',
          countryName: 'Syrian Arab Republic',
          phoneCode: '963',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'SZ',
          countryName: 'Swaziland',
          phoneCode: '268',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TC',
          countryName: 'Turks and Caicos Islands',
          phoneCode: '1-649',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TD',
          countryName: 'Chad',
          phoneCode: '235',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TF',
          countryName: 'French Southern Territories',
          phoneCode: '262',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TG',
          countryName: 'Togo',
          phoneCode: '228',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TH',
          countryName: 'Thailand',
          phoneCode: '66',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TJ',
          countryName: 'Tajikistan',
          phoneCode: '992',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TK',
          countryName: 'Tokelau',
          phoneCode: '690',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TL',
          countryName: 'Timor-Leste',
          phoneCode: '670',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TM',
          countryName: 'Turkmenistan',
          phoneCode: '993',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TN',
          countryName: 'Tunisia',
          phoneCode: '216',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TO',
          countryName: 'Tonga',
          phoneCode: '676',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TR',
          countryName: 'Turkey',
          phoneCode: '90',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TT',
          countryName: 'Trinidad and Tobago',
          phoneCode: '1-868',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TV',
          countryName: 'Tuvalu',
          phoneCode: '688',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TW',
          countryName: 'Taiwan, Republic of China',
          phoneCode: '886',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'TZ',
          countryName: 'United Republic of Tanzania',
          phoneCode: '255',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'UA',
          countryName: 'Ukraine',
          phoneCode: '380',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'UG',
          countryName: 'Uganda',
          phoneCode: '256',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'US',
          countryName: 'United States',
          phoneCode: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'UY',
          countryName: 'Uruguay',
          phoneCode: '598',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'UZ',
          countryName: 'Uzbekistan',
          phoneCode: '998',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'VA',
          countryName: 'Holy See (Vatican City State)',
          phoneCode: '379',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'VC',
          countryName: 'Saint Vincent and the Grenadines',
          phoneCode: '1-784',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'VE',
          countryName: 'Venezuela',
          phoneCode: '58',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'VG',
          countryName: 'British Virgin Islands',
          phoneCode: '1-284',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'VI',
          countryName: 'US Virgin Islands',
          phoneCode: '1-340',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'VN',
          countryName: 'Vietnam',
          phoneCode: '84',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'VU',
          countryName: 'Vanuatu',
          phoneCode: '678',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'WF',
          countryName: 'Wallis and Futuna',
          phoneCode: '681',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'WS',
          countryName: 'Samoa',
          phoneCode: '685',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'XK',
          countryName: 'Kosovo',
          phoneCode: '383',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'YE',
          countryName: 'Yemen',
          phoneCode: '967',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'YT',
          countryName: 'Mayotte',
          phoneCode: '262',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ZA',
          countryName: 'South Africa',
          phoneCode: '27',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ZM',
          countryName: 'Zambia',
          phoneCode: '260',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          countryCode: 'ZW',
          countryName: 'Zimbabwe',
          phoneCode: '263',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Countries', null, {});
  },
};
